### PR TITLE
srisri-prod-app26-wo 143256

### PR DESCRIPTION
**Pull request by srisrijana**
hi  naresh 
    
 I changed the server detailes in srisri-prod-app26.Accept the approvel to make changes
@unixnaresh 
@Jpavanganugula

### CODE REVIEW

**Comment by srisrijana** [comment]
approve the changes

**Review by Jpavanganugula — COMMENTED** [review]
on which task you did it?

**Comment by srisrijana** [comment]
Not for any task, server information is wrongly enterd so i just modified
it

**Review by Jpavanganugula — APPROVED** [review]
LGTM

**Pull request merged**
