### PR TITLE
satish-prod-app20 server details work order #17k61a04d9

### PR DESCRIPTION
**Pull request by satishkokkirala**
Hai naresh,

                Added a new server cloud please take a look and and approve this pr as soon as possible 

Thanks& regards
K.satish
bat22a

### CODE REVIEW

**Review by Jpavanganugula — COMMENTED** [review]
work order no wrong

**Review by Jpavanganugula — CHANGES_REQUESTED** [review]
change work orderno

**Comment by satishkokkirala** [comment]
Hi team,
            Please take a look for changed a workorder  no
thank you
k.satish

**Review by Jpavanganugula — APPROVED** [review]
WO to change from next time it wont looks like mentioned.

**Pull request merged**
